[providers]
python = "3.11"

[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "python311Packages.wheel",
  "gcc",
  "pkg-config",
  "cairo",
  "pango",
  "gdk-pixbuf",
  "libffi",
  "openssl",
  "zlib",
  "libjpeg",
  "libpng",
  "freetype",
  "fontconfig"
]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn raizdigital.wsgi:application --host 0.0.0.0 --port $PORT"