# Generated by Django 3.2.25 on 2025-05-20 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_noticia', models.ForeignKey(db_column='id_noticia', on_delete=django.db.models.deletion.CASCADE, to='core.noticia')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'verbose_name': 'Like de noticia',
                'verbose_name_plural': 'Likes de noticias',
                'db_table': 'raiz.noticia_likes',
                'unique_together': {('id_noticia', 'id_usuario')},
            },
        ),
    ]
